#baseURL = '//localhost'
baseURL = 'https://francescodelduchetto.github.io/LincolnRobocupWebsite/'
canonifyURLS = true
languageCode = 'en-gb'
title = 'LCASTOR website'
theme = 'lincoln_robocup_theme'
